name: Test workflow in GCP
on:
  push:
    branches:
      - main

jobs:
  test-job:
    name: Test job
    runs-on: self-hosted

    permissions:
      contents: read
      id-token: write

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          project_id: meld-proj-services-2865728b
          workload_identity_provider: projects/214335469585/locations/global/workloadIdentityPools/github-actions-id-pool/providers/github-actions-provider
          service_account: github-actions-service-account@meld-proj-services-2865728b.iam.gserviceaccount.com
          # access_token_lifetime: 300s

      - id: run-test-command
        name: Run test command
        run: |
          echo "Running test command"
          hostname
          gcloud version
